### ISSUE TITLE
Updating the speed of object as score increases kivy game

### ISSUE THREAD

**Issue by Afani-Ctrl** [Afani-Ctrl/TRIXX-KIVY#1]
Currently developing a game and I am stuck on my final steps. I would like the following to happen when the score reaches i.e 50

background
increase the speed of pipes
I have tried inputting a update_score under my MainApp(MDApp) and adding an if statement however I feel like my issue lies with making reference to the score itself.

**_This is under my class background(widget) which holds my __init___**

```
score = NumericProperty(1)
score = 0

def update(self, *args):
    self.score += 1
    self.ids.score.text ="SCORE: " + str(self.score)
```

**_Extract from my MainApp(MDApp)_**

```
   def move_pipes(self, time_passed):
         for pipe in self.pipes:
         pipe.x -= time_passed * 180
```

**_id: score in .kv file_**

```
   MDLabel:
        id: score
        size_hint_y: None
        height: 96
        text: " "
        text_size: "BUTTON"
        font_size: 30
        pos_hint: {'center_x':0.905,'center_y':0.9}
```
